-- Baseline for the ledger database, owned by ledger-service.
--
-- Deliberately empty. A table arrives in the migration that introduces the feature needing
-- it, so the history of this schema starts at a known point rather than with a table that
-- nothing reads yet.
