server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-service
              uri: http://identity-service:8081
              predicates:
                - Path=/api/v1/identity/**
            - id: ledger-service
              uri: http://ledger-service:8082
              predicates:
                - Path=/api/v1/ledger/**
            - id: payment-service
              uri: http://payment-service:8083
              predicates:
                - Path=/api/v1/payments/**
            - id: risk-service
              uri: http://risk-service:8084
              predicates:
                - Path=/api/v1/risk/**
            - id: notification-service
              uri: http://notification-service:8085
              predicates:
                - Path=/api/v1/notifications/**
            - id: identity-service-health
              uri: http://identity-service:8081
              predicates:
                - Path=/internal/identity-service/**
              filters:
                - StripPrefix=2
            - id: ledger-service-health
              uri: http://ledger-service:8082
              predicates:
                - Path=/internal/ledger-service/**
              filters:
                - StripPrefix=2
            - id: payment-service-health
              uri: http://payment-service:8083
              predicates:
                - Path=/internal/payment-service/**
              filters:
                - StripPrefix=2
            - id: risk-service-health
              uri: http://risk-service:8084
              predicates:
                - Path=/internal/risk-service/**
              filters:
                - StripPrefix=2
            - id: notification-service-health
              uri: http://notification-service:8085
              predicates:
                - Path=/internal/notification-service/**
              filters:
                - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    correlation: "[%X{correlationId:-}] "
