-- Where an event waits until somebody publishes it.
--
-- This table is what makes a state change and the announcement of it one thing. The row is
-- written in the same transaction as the change, so there is no arrangement of failures that
-- leaves the money moved and nobody told, or everybody told about money that never moved.
-- A broker cannot join a database transaction; a table in the same database can.
--
-- Each service that produces events owns its own copy, because each service owns its own
-- schema. The shape is identical everywhere on purpose: the code that writes to it is shared.

create table outbox_event (
    -- Generated by the producer before the row is written, and never regenerated. This is
    -- what a consumer deduplicates on, so it has to survive every redelivery of the event.
    id uuid primary key,
    type text not null,
    -- The shape of the payload. A consumer that predates a change can say so rather than
    -- guess what it is looking at.
    version integer not null,
    aggregate_type text not null,
    -- Also the ordering key. Events about one payment stay in order relative to each other,
    -- which is the only ordering a partitioned log can honestly offer.
    aggregate_id uuid not null,
    merchant_id uuid not null,
    -- When the thing happened, which is not when anybody publishes it, and not when this row
    -- was written either once a relay is retrying.
    occurred_at timestamptz not null,
    -- The request that caused this, so a trace crosses the gap between a call and everything
    -- that happened because of it.
    correlation_id text,
    payload jsonb not null,
    -- Null until published. MIZ-48 is what sets it; until then every row here is unsent and
    -- that is correct, because nothing publishes yet.
    published_at timestamptz
);

-- What a relay asks for: the unpublished, oldest first. Partial, because the answer to that
-- question shrinks to nothing while the table itself grows without limit.
create index outbox_event_unpublished_idx
    on outbox_event (occurred_at)
    where published_at is null;

-- For reading the history of one payment, and for a relay that has to preserve order within
-- an aggregate rather than across all of them.
create index outbox_event_aggregate_idx on outbox_event (aggregate_id, occurred_at);

-- An event is a record of something that happened, so it is not edited and not deleted. The
-- one column that changes is published_at, and only from null to a time. The trigger below is
-- what makes that true against anything writing to this table, including psql.
--
-- Deleting is left alone: an event that has been published and is older than the retention
-- anybody needs is rubbish, not evidence, and a table that only grows is its own outage.
create or replace function outbox_event_is_append_only() returns trigger as $$
begin
    if (new.id, new.type, new.version, new.aggregate_type, new.aggregate_id, new.merchant_id,
        new.occurred_at, new.correlation_id, new.payload)
       is distinct from
       (old.id, old.type, old.version, old.aggregate_type, old.aggregate_id, old.merchant_id,
        old.occurred_at, old.correlation_id, old.payload) then
        raise exception 'an event records what happened and cannot be changed; only '
                        'published_at may be set';
    end if;
    if old.published_at is not null and new.published_at is distinct from old.published_at then
        raise exception 'an event that has been published cannot be unpublished';
    end if;
    return new;
end;
$$ language plpgsql;

create trigger outbox_event_no_rewriting
    before update on outbox_event
    for each row execute function outbox_event_is_append_only();
